#22 JAN
# PROGRAM 1
X=int(input("Enter first number"))
Y=int(input("Enter second number"))
SUM= (X+Y)
print ("SUM of the two numbers is" , SUM)

#PROGRAM2 
num_str="25"
X=int(num_str)
Y=float(num_str)
print(type(X))
print(type(Y))
sum=(X+Y)
print(sum)


#PROGRAM 3 
X=int(input("Enter first number"))
Y=int(input("Enter first number"))
Sum=(X+Y)
Difference=(X-Y)
Product=(X*Y)
Quotient=(X/Y)
print("Sum of the numbers is", Sum)
print("Difference of the number is ", Difference)
print("Product of the numbers is", Product)
print("Quotient of the numbers is", Quotient)


#PROGRAM 4
str="hello"
Q=str.upper()
print(Q)
new_str=str.replace("hello","hi")
print(new_str) 